In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])
print (arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
# 0으로 초기화된 배열
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# 빈값으로 만들어진 배열
arr = np.empty((3,4))
print(arr)

[[1.60086755e-316 2.47032823e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 8.60952352e-072 7.17333184e-091 6.40179198e+170]
 [2.32504051e-057 1.39497457e-047 3.99910963e+252 1.46030983e-319]]


In [ ]:
# 1로 가득찬 배열을 만든다
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# 배열의 생성
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# ndarray 배열의 묘양, 차수, 데이터 타입 확인

arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr.shape

(2, 3)

In [ ]:
arr.ndim

2

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr_float = arr.astype(np.float64)
arr_float.dtype

dtype('float64')

In [ ]:
arr_str = np.array(['1','2','3'])
arr_str.dtype

dtype('<U1')

In [ ]:
int_str = arr_str.astype(np.int64)
int_str.dtype

dtype('int64')

In [ ]:
# ndarray 배열의 연산

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

arr1 + arr2
np.add(arr1,arr2)

array([[ 6,  8],
       [10, 12]])

In [ ]:
arr1 * arr2

array([[ 5, 12],
       [21, 32]])

In [ ]:
np.multiply(arr1,arr2)

array([[ 5, 12],
       [21, 32]])

In [ ]:
# ndarray 배열 슬라이싱 하기

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_1 = arr[:2,1:3]
print(arr_1)

[[2 3]
 [5 6]]


In [ ]:
arr[0,2]

3

In [ ]:
arr[[0,1,2],[2,0,1]]

array([3, 4, 8])

In [ ]:
idx=arr>3
print(idx)

[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
print(arr[idx])

[4 5 6 7 8 9]


In [ ]:
redwine = np.loadtxt(fname='winequality-red.csv',delimiter=';',skiprows=1)
print(redwine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [ ]:
print(redwine.sum())
print(redwine.mean())

152084.78194
7.926036165311652


In [ ]:
# 축(axis)
print(redwine.sum(axis=0))
print(redwine.sum(axis=1))

[13303.1       843.985     433.29     4059.55      139.859   25384.
 74302.       1593.79794  5294.47     1052.38    16666.35     9012.     ]
[ 74.5438  123.0548   99.699   ... 100.48174 105.21547  92.49249]


In [ ]:
redwine[:,0]
redwine[:,0]

array([7.4, 7.8, 7.8, ..., 6.3, 5.9, 6. ])

In [ ]:
redwine[:,0].mean()

8.31963727329581

In [ ]:
redwine.min(axis=0)

array([4.6    , 0.12   , 0.     , 0.9    , 0.012  , 1.     , 6.     ,
       0.99007, 2.74   , 0.33   , 8.4    , 3.     ])